apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example3
    spec:
      containers:
      - name: example-container
        image: example-image
        ports:
        - containerPort: 8080
